version: "1"
services:
  postgres_test:
    build:
      dockerfile: postgres.Dockerfile
    restart: always
    ports:
      - "5432:5432"
    networks:
      - tests
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_booking_db
      - NODE_ENV=test
networks:
  tests:
    name: tests